#
# An example workflow using the Accurics Action
#
on:
  push:
    branches:
      - master

jobs:
  accurics_test_job:
    runs-on: ubuntu-latest
    name: My GitHub Workflow With Accurics
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Accurics Scan
        uses: accurics/accurics-action@v1.1
        id: accurics
        env:
          # Credentials are required by Terraform. They can be specified using any method that Terraform accepts
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          # A specific Terraform version can be chosen (default=latest)
          terraform-version: 0.12.28
          # Specify any Terraform plan args here. Variables can be specified as follows (enclosed in single quotes)
          plan-args: '-var public_key_path=terraform-poc01.pub -var key_name=terraform-poc01'
          # Specify the ENV_ID and APP_ID from the config file
          env-id: ${{ secrets.PROD_ENV_ID }}
          app-id: ${{ secrets.PROD_APP_ID }}
          # Specify the location to the repository
          repo: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
          # Fail the build when violations are found:
          fail-on-violations: true
          # Fail the build on all errors
#          fail-on-all-errors: false
      - name: Display statistics
        run: '
            echo "Environment Name           : ${{ steps.accurics.outputs.env-name }}";
            echo "Violation Count            : ${{ steps.accurics.outputs.num-violations }}";
            echo "Resource Count             : ${{ steps.accurics.outputs.num-resources }}";
            echo "Native Resources           : ${{ steps.accurics.outputs.native }}";
            echo "Inherited Resources        : ${{ steps.accurics.outputs.inherited }}";
            echo "High-Severity Violations   : ${{ steps.accurics.outputs.high }}";
            echo "Medium-Severity Violations : ${{ steps.accurics.outputs.medium }}";
            echo "Low-Severity Violations    : ${{ steps.accurics.outputs.low }}";
            echo "Drift                      : ${{ steps.accurics.outputs.drift }}";
            echo "IaC Drift                  : ${{ steps.accurics.outputs.iacdrift }}";
            echo "Cloud Drift                : ${{ steps.accurics.outputs.clouddrift }}";
            echo ""
          '
